version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: tmdt-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-tmdtdb}
      MYSQL_USER: ${MYSQL_USER:-tmdtuser}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-tmdtpassword}
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./backend/src/main/resources/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - tmdt-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: tmdt-backend
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/${MYSQL_DATABASE:-tmdtdb}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: ${MYSQL_USER:-tmdtuser}
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_PASSWORD:-tmdtpassword}
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      APP_JWT_SECRET: ${JWT_SECRET:-tmdt123456789tmdtsecretkey987654321}
      APP_JWT_EXPIRATION_MS: ${JWT_EXPIRATION:-86400000}
      FILE_UPLOAD_DIR: /app/uploads
    ports:
      - "8080:8080"
    volumes:
      - ./backend/uploads:/app/uploads
    networks:
      - tmdt-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: tmdt-frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "3000:80"
    networks:
      - tmdt-network

volumes:
  mysql-data:

networks:
  tmdt-network:
    driver: bridge 