version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: tmdt-backend
    restart: always
    environment:
      # Cấu hình kết nối MySQL bên ngoài Docker
      # Sử dụng host.docker.internal để kết nối tới localhost của máy chủ
      SPRING_DATASOURCE_URL: jdbc:mysql://${DB_HOST:-host.docker.internal}:${DB_PORT:-3306}/${DB_NAME:-tmdt}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: ${DB_USER:-webuser}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD:-123!}
      SPRING_JPA_HIBERNATE_DDL_AUTO: ${HIBERNATE_DDL:-update}
      
      # Cấu hình debug và logging
      LOGGING_LEVEL_ROOT: INFO
      LOGGING_LEVEL_COM_EXAMPLE_TMDT: DEBUG
      LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY: DEBUG
      LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_WEB: DEBUG
      LOGGING_LEVEL_ORG_HIBERNATE_SQL: DEBUG
      LOGGING_LEVEL_COM_EXAMPLE_TMDT_SECURITY: TRACE
      
      # In thông tin kết nối khi khởi động
      APP_PRINT_CONFIG: "true"
      
      # Bảo mật
      SPRING_SECURITY_PERMIT_ACTUATOR: "true"
      # Cho phép các endpoints công khai - sửa đúng đường dẫn (/auth/signin thay vì /api/auth/signin)
      SPRING_SECURITY_PERMITALL: "/api/products/**,/api/categories/**,/auth/**,/api/auth/**,/actuator/**,/api/**"
      # Vô hiệu hóa CSRF
      SPRING_SECURITY_CSRF_DISABLED: "true"
      
      # JWT Configuration
      APP_JWT_SECRET: ${JWT_SECRET:-mySecretKey123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ}
      APP_JWT_EXPIRATION_MS: ${JWT_EXPIRATION:-86400000}
      
      # Cấu hình khác
      FILE_UPLOAD_DIR: /app/uploads
      WEBSOCKET_PORT: 8088
    ports:
      - "${BACKEND_PORT:-8080}:8080"
      - "${WS_PORT:-8088}:8088"
    volumes:
      - ./backend/uploads:/app/uploads
      - ./backend/logs:/app/logs
    networks:
      - tmdt-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health", "||", "curl", "-f", "http://localhost:8080/api/products"]
      interval: 20s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: tmdt-frontend
    restart: always
    depends_on:
      backend:
        condition: service_healthy
    environment:
      BACKEND_HOST: backend
      BACKEND_PORT: 8080
      BACKEND_WS_PORT: 8088
      # Đảm bảo các biến môi trường cho React được đặt chính xác
      REACT_APP_API_URL: /api
      REACT_APP_WS_URL: /ws
    ports:
      - "${FRONTEND_PORT:-80}:80"
    networks:
      - tmdt-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 20s

volumes:
  mysql-data:
    name: tmdt-mysql-data

networks:
  tmdt-network:
    name: tmdt-network
    driver: bridge 