spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tmdt?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
        jdbc:
          lob:
            non_contextual_creation: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  mvc:
    servlet:
      path: /
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  web:
    resources:
      add-mappings: true
    cors:
      allowed-origins: '*'
      allowed-methods: GET,POST,PUT,DELETE,OPTIONS
      allowed-headers: '*'
      allow-credentials: false
      max-age: 3600

server:
  port: 8080
  servlet:
    context-path: /api
    encoding:
      charset: UTF-8
      enabled: true
      force: true

# JWT Properties
app:
  jwt:
    secret: tmdt123SecretKey
    expirationMs: 86400000

# Logging Configuration
logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: DEBUG
    org.hibernate: ERROR
    com.example.tmdt: DEBUG
    com.example.tmdt.security: DEBUG
    com.example.tmdt.controller: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: ./logs/application.log
    max-size: 10MB
    max-history: 30

# OpenAPI & Swagger Configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method 